{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.3.1.10:9100\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.3.1.10:9100\"}[1m])) by (instance) * 100)",
     "legendFormat": "1m"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.3.1.10:9100\"}[5m])) by (instance) * 100)",
     "legendFormat": "5m"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.3.1.10:9100\"}[15m])) by (instance) * 100)",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"10.3.1.10:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NVME",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\",fstype!=\"fuse.lxcfs\", instance=\"10.3.1.10:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}